name = "Material Blog"
license = "MIT"
licenselink = "https://github.com/channprj/hugo-material-blog/blob/master/LICENSE.md"
description = "A material design theme for blog."
homepage = "https://github.com/channprj/hugo-material-blog"
tags = ["material", "documentation", "docs", "blog", "google analytics", "responsive"]
features = []
min_version = 0.20

[author]
  name = "CHANN"
  homepage = "https://github.com/channprj"

[original]
  name = "Digitalcraftsman"
  homepage = "https://github.com/digitalcraftsman"
  repo = "https://github.com/digitalcraftsman/hugo-material-docs"
