baseurl = "https://example.org/"
languageCode = "ko-kr"
title = "Material Blog"
theme = "hugo-material-blog"
metadataformat = "yaml"
canonifyurls = true
pygmentsCodeFences = true
pygmentsStyle = "friendly"
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[permalinks]
	post = "/post/:filename/"
	fixed = "/:filename/"

[params]
	# General information
	author = "Digitalcraftsman"
	description = "A material design theme for documentations."
	copyright = "Released under the MIT license"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/digitalcraftsman/hugo-material-docs"

	version = "1.0.0"
	logo = "images/logo.png"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "red"
    	accent  = "teal"

    [params.font]
    	text = "Roboto"
    	code = "Roboto Mono"


[social]
	twitter = ""
	github  = "digitalcraftsman"
	email   = "hello@email.com"


[[menu.main]]
	name   = "Home"
	url    = "/"
	weight = 10

[[menu.main]]
	name   = "About"
	url    = "about/"
	weight = 20

[[menu.main]]
	name   = "Posts"
	url    = "post/"
	weight = 30

[[menu.main]]
	name   = "Categories"
	url    = "category/"
	weight = 40


[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
